# cspell: words linkcheck

name: Check Hyperlinks
on: [pull_request]

env:
  SPHINXOPTS: --quiet

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Prepare Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install Python Requirements
        run: pip install -r requirements.txt
      - name: Check for Broken Links
        run: |
          if [ x${RUNNER_DEBUG:+is_set} == x"is_set" ]
          then
            unset SPHINXOPTS
          fi
          make linkcheck
      - name: Upload linkcheck Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: linkcheck-output
          path: 'build/linkcheck/output.*'
